"""add test FK

Revision ID: 0003
Revises: 0002
Create Date: 2023-02-16 14:55:12.805339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_charityproject_name'), ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_charityproject_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_charityproject_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_charityproject_name'), type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
