"""fixed the field

Revision ID: 0005
Revises: 0004
Create Date: 2023-02-17 23:53:16.753020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('create_data')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('create_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_data', sa.DATETIME(), nullable=True))
        batch_op.drop_column('create_date')

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_data', sa.DATETIME(), nullable=True))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
